const E=id=>document.getElementById(id);
const els={canvas:E('simCanvas'),flavourCanvas:E('flavourCanvas'),playPauseBtn:E('playPauseBtn'),resetBtn:E('resetBtn'),defaultPresetBtn:E('defaultPresetBtn'),nearThresholdPresetBtn:E('nearThresholdPresetBtn'),bcPeriodicBtn:E('bcPeriodicBtn'),bcDirichletBtn:E('bcDirichletBtn'),bcNeumannBtn:E('bcNeumannBtn'),g:E('g'),gNumber:E('gNumber'),kappa1:E('kappa1'),kappa1Number:E('kappa1Number'),kappa2:E('kappa2'),kappa2Number:E('kappa2Number'),L:E('L'),LNumber:E('LNumber'),N:E('N'),NNumber:E('NNumber'),dt:E('dt'),dtNumber:E('dtNumber'),topCharge:E('topCharge'),topChargeNumber:E('topChargeNumber'),relaxSteps:E('relaxSteps'),relaxStepsNumber:E('relaxStepsNumber'),substeps:E('substeps'),substepsNumber:E('substepsNumber'),viewMode:E('viewMode'),bcFormula:E('bcFormula'),initialFormula:E('initialFormula'),bcReadout:E('bcReadout'),topChargeReadout:E('topChargeReadout'),timeReadout:E('timeReadout'),energyReadout:E('energyReadout'),dxReadout:E('dxReadout'),phiCReadout:E('phiCReadout'),phiSReadout:E('phiSReadout'),qSReadout:E('qSReadout'),consistencyReadout:E('consistencyReadout'),messageReadout:E('messageReadout')};
const ctx=els.canvas.getContext('2d'), fctx=els.flavourCanvas.getContext('2d');
const SQRT2=Math.sqrt(2), SQRT_PI=Math.sqrt(Math.PI), ALPHA=Math.sqrt(2*Math.PI), BETA=2*SQRT_PI, DELTA=ALPHA;
let sim=null,running=false,bcType='periodic';
const pairs=[['g','gNumber'],['kappa1','kappa1Number'],['kappa2','kappa2Number'],['L','LNumber'],['N','NNumber'],['dt','dtNumber'],['topCharge','topChargeNumber'],['relaxSteps','relaxStepsNumber'],['substeps','substepsNumber']];
function params(){return{g:+els.gNumber.value,kappa1:+els.kappa1Number.value,kappa2:+els.kappa2Number.value,L:+els.LNumber.value,N:Math.round(+els.NNumber.value),dt:+els.dtNumber.value,z:Math.round(+els.topChargeNumber.value),relaxSteps:Math.round(+els.relaxStepsNumber.value),substeps:Math.round(+els.substepsNumber.value),viewMode:els.viewMode.value,bcType};}
function setBC(b){bcType=b;[els.bcPeriodicBtn,els.bcDirichletBtn,els.bcNeumannBtn].forEach(x=>x.classList.remove('active'));({periodic:els.bcPeriodicBtn,dirichlet:els.bcDirichletBtn,neumann:els.bcNeumannBtn}[b]).classList.add('active');reinitialize();}
function formula(){let bc;if(bcType==='periodic')bc='\\[\\phi_a(-L/2,t)=\\phi_a(L/2,t),\\qquad \\partial_x\\phi_a(-L/2,t)=\\partial_x\\phi_a(L/2,t),\\quad a=c,s.\\]';else if(bcType==='dirichlet')bc='\\[\\phi_c(\\pm L/2,t)=0,\\qquad \\phi_s(-L/2,t)=0,\\qquad \\phi_s(L/2,t)=z\\sqrt{2\\pi}.\\]';else bc='\\[\\partial_x\\phi_c(\\pm L/2,t)=0,\\qquad \\partial_x\\phi_s(\\pm L/2,t)=0.\\]';els.bcFormula.innerHTML=bc;els.initialFormula.innerHTML='\\[\\partial_t\\phi_c(x,0)=\\partial_t\\phi_s(x,0)=\\partial_t\\phi_1(x,0)=\\partial_t\\phi_2(x,0)=0.\\]\\[z=0:\\; \\phi_2(x,0)=0,\\; \\phi_1(-L/4,0)=\\phi_1(L/4,0)=\\sqrt{\\pi}/2.\\]\\[z\\ne0:\\; \\phi_1(0,0)=\\frac z2\\sqrt{\\pi},\\quad \\phi_s(L/2,0)-\\phi_s(-L/2,0)=z\\sqrt{2\\pi}.\\]';if(window.MathJax)window.MathJax.typesetPromise([els.bcFormula,els.initialFormula]);}
function reinitialize(){running=false;els.playPauseBtn.textContent='Play';initialize();}
function kink(x,x0,w){return 2/SQRT_PI*Math.atan(Math.exp((x-x0)/w));}
function antikink(x,x0,w){return SQRT_PI-kink(x,x0,w);}
function smoothPinned(phi, fixed, p){const n=phi.length,dx=p.L/p.N,dtau=.18*dx*dx;for(let r=0;r<p.relaxSteps;r++){const old=phi.slice();for(let i=1;i<n-1;i++){if(fixed[i])continue;const lap=(old[i+1]-2*old[i]+old[i-1])/(dx*dx);const force=lap-(p.g*p.g/2)*old[i]-SQRT_PI*Math.sin(BETA*old[i]);phi[i]+=dtau*force;}for(let i=0;i<n;i++)if(fixed[i]!==null)phi[i]=fixed[i];}}
function buildInitial(p){const n=p.N,dx=p.L/p.N,x=new Float64Array(n),phi1=new Float64Array(n),phi2=new Float64Array(n);const w=p.width||Math.max(1,2/(Math.sqrt(p.g*p.g/2+2*Math.PI*Math.max(p.kappa1,.1))));for(let i=0;i<n;i++)x[i]=-p.L/2+i*dx;
 if(bcType==='periodic'){for(let i=0;i<n;i++){phi1[i]=kink(x[i],-p.L/4,w)-kink(x[i],p.L/4,w);phi2[i]=0;}}
 else if(p.z===0){for(let i=0;i<n;i++){phi1[i]=kink(x[i],-p.L/4,w)-kink(x[i],p.L/4,w);phi2[i]=0;}let fixed=new Array(n).fill(null);fixed[0]=0;fixed[n-1]=0;smoothPinned(phi1,fixed,p);}
 else {const z=p.z,amp=z*SQRT_PI;for(let i=0;i<n;i++)phi1[i]=amp*0.5*(1+Math.tanh(x[i]/w));let fixed=new Array(n).fill(null);fixed[0]=0;fixed[n-1]=amp;fixed[Math.floor(n/2)]=0.5*amp;smoothPinned(phi1,fixed,p);for(let i=0;i<n;i++)phi2[i]=0;}
 const phiC=new Float64Array(n),phiS=new Float64Array(n);for(let i=0;i<n;i++){phiC[i]=(phi1[i]+phi2[i])/SQRT2;phiS[i]=(phi1[i]-phi2[i])/SQRT2;}if(bcType!=='periodic'){phiC[0]=0;phiC[n-1]=0;if(p.z!==0){phiS[0]=0;phiS[n-1]=p.z*DELTA;phi1[0]=(phiC[0]+phiS[0])/SQRT2;phi1[n-1]=(phiC[n-1]+phiS[n-1])/SQRT2;phi2[0]=(phiC[0]-phiS[0])/SQRT2;phi2[n-1]=(phiC[n-1]-phiS[n-1])/SQRT2;}}return{x,phiC,phiS,phi1,phi2};}
function initialize(){const p=params();p.width=Math.max(.15,+((E('widthNumber')||{}).value||1))*2/(Math.sqrt(p.g*p.g/2+2*Math.PI*Math.max(p.kappa1,.05)));const dx=p.L/p.N;const init=buildInitial(p);const z=new Float64Array(p.N);sim={...p,dx,t:0,x:init.x,phiC:init.phiC,phiS:init.phiS,piC:z.slice(),piS:z.slice(),phi1:init.phi1,phi2:init.phi2,pi1:z.slice(),pi2:z.slice()};formula();updateReadout('initialized');draw();drawCheck();}
function lap(f){const n=f.length,out=new Float64Array(n),iv=1/(sim.dx*sim.dx);for(let i=0;i<n;i++){let im=i-1,ip=i+1;if(sim.bcType==='periodic'){if(i===0)im=n-1;if(i===n-1)ip=0;}else{if(i===0){im=sim.bcType==='neumann'?1:0;ip=1;}if(i===n-1){ip=sim.bcType==='neumann'?n-2:n-1;im=n-2;}}out[i]=(f[ip]-2*f[i]+f[im])*iv;}return out;}
function enforce(){const n=sim.phiC.length;if(sim.bcType==='periodic')return;if(sim.bcType==='dirichlet'){sim.phiC[0]=0;sim.phiC[n-1]=0;sim.phiS[0]=0;sim.phiS[n-1]=sim.z*DELTA;sim.piC[0]=sim.piC[n-1]=sim.piS[0]=sim.piS[n-1]=0;sim.phi1[0]=(sim.phiC[0]+sim.phiS[0])/SQRT2;sim.phi2[0]=(sim.phiC[0]-sim.phiS[0])/SQRT2;sim.phi1[n-1]=(sim.phiC[n-1]+sim.phiS[n-1])/SQRT2;sim.phi2[n-1]=(sim.phiC[n-1]-sim.phiS[n-1])/SQRT2;}else{sim.phiC[0]=sim.phiC[1];sim.phiC[n-1]=sim.phiC[n-2];sim.phiS[0]=sim.phiS[1];sim.phiS[n-1]=sim.phiS[n-2];sim.phi1[0]=sim.phi1[1];sim.phi1[n-1]=sim.phi1[n-2];sim.phi2[0]=sim.phi2[1];sim.phi2[n-1]=sim.phi2[n-2];}}
function accCS(pc,ps){const n=pc.length,lc=lap(pc),ls=lap(ps),ac=new Float64Array(n),as=new Float64Array(n);for(let i=0;i<n;i++){const a1=ALPHA*(pc[i]+ps[i]),a2=ALPHA*(pc[i]-ps[i]);ac[i]=lc[i]-sim.g*sim.g*pc[i]-.5*ALPHA*sim.kappa1*Math.sin(a1)-.5*ALPHA*sim.kappa2*Math.sin(a2);as[i]=ls[i]-.5*ALPHA*sim.kappa1*Math.sin(a1)+.5*ALPHA*sim.kappa2*Math.sin(a2);}return{ac,as};}
function acc12(p1,p2){const n=p1.length,l1=lap(p1),l2=lap(p2),a1=new Float64Array(n),a2=new Float64Array(n);for(let i=0;i<n;i++){const ch=.5*sim.g*sim.g*(p1[i]+p2[i]);a1[i]=l1[i]-ch-SQRT_PI*sim.kappa1*Math.sin(BETA*p1[i]);a2[i]=l2[i]-ch-SQRT_PI*sim.kappa2*Math.sin(BETA*p2[i]);}return{a1,a2};}
function step(){const n=sim.phiC.length,dt=sim.dt,{ac,as}=accCS(sim.phiC,sim.phiS),{a1,a2}=acc12(sim.phi1,sim.phi2);let pc=new Float64Array(n),ps=new Float64Array(n),p1=new Float64Array(n),p2=new Float64Array(n),vc=new Float64Array(n),vs=new Float64Array(n),v1=new Float64Array(n),v2=new Float64Array(n);for(let i=0;i<n;i++){vc[i]=sim.piC[i]+.5*dt*ac[i];vs[i]=sim.piS[i]+.5*dt*as[i];v1[i]=sim.pi1[i]+.5*dt*a1[i];v2[i]=sim.pi2[i]+.5*dt*a2[i];pc[i]=sim.phiC[i]+dt*vc[i];ps[i]=sim.phiS[i]+dt*vs[i];p1[i]=sim.phi1[i]+dt*v1[i];p2[i]=sim.phi2[i]+dt*v2[i];}sim.phiC=pc;sim.phiS=ps;sim.phi1=p1;sim.phi2=p2;enforce();const A=accCS(sim.phiC,sim.phiS),B=acc12(sim.phi1,sim.phi2);for(let i=0;i<n;i++){sim.piC[i]=vc[i]+.5*dt*A.ac[i];sim.piS[i]=vs[i]+.5*dt*A.as[i];sim.pi1[i]=v1[i]+.5*dt*B.a1[i];sim.pi2[i]=v2[i]+.5*dt*B.a2[i];}enforce();sim.t+=dt;}
function maxAbs(a){let m=0;for(const v of a)m=Math.max(m,Math.abs(v));return m;}function minV(a){let m=Infinity;for(const v of a)m=Math.min(m,v);return m;}function maxV(a){let m=-Infinity;for(const v of a)m=Math.max(m,v);return m;}
function converted(){const n=sim.phi1.length,c=new Float64Array(n),s=new Float64Array(n),dc=new Float64Array(n),ds=new Float64Array(n);for(let i=0;i<n;i++){c[i]=(sim.phi1[i]+sim.phi2[i])/SQRT2;s[i]=(sim.phi1[i]-sim.phi2[i])/SQRT2;dc[i]=c[i]-sim.phiC[i];ds[i]=s[i]-sim.phiS[i];}return{c,s,dc,ds};}
function energy(){let sum=0,n=sim.phiC.length;for(let i=0;i<n;i++){let ip=i+1<n?i+1:(sim.bcType==='periodic'?0:i),im=i>0?i-1:(sim.bcType==='periodic'?n-1:i);const gc=(sim.phiC[ip]-sim.phiC[im])/(2*sim.dx),gs=(sim.phiS[ip]-sim.phiS[im])/(2*sim.dx),a1=ALPHA*(sim.phiC[i]+sim.phiS[i]),a2=ALPHA*(sim.phiC[i]-sim.phiS[i]);sum+=.5*sim.piC[i]**2+.5*sim.piS[i]**2+.5*gc**2+.5*gs**2+.5*sim.g**2*sim.phiC[i]**2-.5*sim.kappa1*Math.cos(a1)-.5*sim.kappa2*Math.cos(a2);}return sum*sim.dx;}
function updateReadout(msg){const cv=converted();els.bcReadout.textContent=sim.bcType;els.topChargeReadout.textContent=sim.z;els.timeReadout.textContent=sim.t.toFixed(2);els.energyReadout.textContent=energy().toFixed(4);els.dxReadout.textContent=sim.dx.toFixed(4);els.phiCReadout.textContent=(maxAbs(sim.phiC)/DELTA).toFixed(3);els.phiSReadout.textContent=(maxAbs(sim.phiS)/DELTA).toFixed(3);els.qSReadout.textContent=((sim.phiS[sim.N-1]-sim.phiS[0])/DELTA).toFixed(3);els.consistencyReadout.textContent=Math.max(maxAbs(cv.dc),maxAbs(cv.ds)).toExponential(3);els.messageReadout.textContent=msg;}
function bounds(arrs,step=null){let lo=Infinity,hi=-Infinity;arrs.forEach(a=>{lo=Math.min(lo,minV(a));hi=Math.max(hi,maxV(a));});if(Math.abs(hi-lo)<1e-9){lo-=1;hi+=1;}if(step){let nl=Math.ceil(lo/step),nh=Math.floor(hi/step);if(nl>nh){nl=nh=Math.round((lo+hi)/(2*step));}return{lo:(nl-1)*step,hi:(nh+1)*step,step,nl,nh};}let p=.18*(hi-lo);return{lo:lo-p,hi:hi+p};}
function axes(c,x,y,w,h,b,t){c.strokeStyle='#cbd5e1';c.strokeRect(x,y,w,h);c.fillStyle='#0f172a';c.font='20px sans-serif';c.fillText(t,x,y-12);c.fillStyle='#64748b';c.font='14px sans-serif';c.fillText(b.hi.toFixed(2),x-50,y+14);c.fillText(b.lo.toFixed(2),x-50,y+h);if(b.step)for(let n=b.nl;n<=b.nh;n++){let yy=y+h-((n*b.step-b.lo)/(b.hi-b.lo))*h;c.setLineDash([7,7]);c.beginPath();c.moveTo(x,yy);c.lineTo(x+w,yy);c.stroke();c.setLineDash([]);}}
function curve(c,a,x,y,w,h,b,col,dash=[]){c.strokeStyle=col;c.lineWidth=2.4;c.setLineDash(dash);c.beginPath();for(let i=0;i<a.length;i++){let xx=x+i/(a.length-1)*w,yy=y+h-((a[i]-b.lo)/(b.hi-b.lo))*h;if(i)c.lineTo(xx,yy);else c.moveTo(xx,yy);}c.stroke();c.setLineDash([]);}
function panel(c,a,x,y,w,h,t,col,step){const b=bounds([a],step);axes(c,x,y,w,h,b,t);curve(c,a,x,y,w,h,b,col);}function compare(c,a,b,x,y,w,h,t,col1,col2,step){const bd=bounds([a,b],step);axes(c,x,y,w,h,bd,t);curve(c,a,x,y,w,h,bd,col1);curve(c,b,x,y,w,h,bd,col2,[10,5]);}
function draw(){ctx.clearRect(0,0,els.canvas.width,els.canvas.height);ctx.fillStyle='white';ctx.fillRect(0,0,els.canvas.width,els.canvas.height);const px=64,py=52,gx=38,gy=52,w=(els.canvas.width-2*px-gx)/2,h=(els.canvas.height-2*py-gy)/2;if(sim.viewMode!=='flavour_only'){panel(ctx,sim.phiC,px,py,w,h,'phi_c(x,t)','#2563eb',DELTA);panel(ctx,sim.phiS,px+w+gx,py,w,h,'phi_s(x,t)','#dc2626',DELTA);}if(sim.viewMode!=='charge_only'){let y=py+h+gy;panel(ctx,sim.phi1,px,y,w,h,'phi_1(x,t)','#7c3aed',SQRT_PI);panel(ctx,sim.phi2,px+w+gx,y,w,h,'phi_2(x,t)','#059669',SQRT_PI);}}
function drawCheck(){fctx.clearRect(0,0,els.flavourCanvas.width,els.flavourCanvas.height);fctx.fillStyle='white';fctx.fillRect(0,0,els.flavourCanvas.width,els.flavourCanvas.height);const cv=converted(),px=64,py=52,gx=38,gy=54,w=(els.flavourCanvas.width-2*px-gx)/2,h=(els.flavourCanvas.height-2*py-gy)/2;compare(fctx,sim.phiC,cv.c,px,py,w,h,'phi_c: direct vs reconstructed','#2563eb','#f97316',DELTA);compare(fctx,sim.phiS,cv.s,px+w+gx,py,w,h,'phi_s: direct vs reconstructed','#dc2626','#0ea5e9',DELTA);let y=py+h+gy;panel(fctx,cv.dc,px,y,w,h,'Delta phi_c','#111827',null);panel(fctx,cv.ds,px+w+gx,y,w,h,'Delta phi_s','#ef4444',null);}
function tick(){if(running){for(let k=0;k<sim.substeps;k++)step();updateReadout('running');draw();drawCheck();}requestAnimationFrame(tick);}
els.playPauseBtn.onclick=()=>{running=!running;els.playPauseBtn.textContent=running?'Pause':'Play';updateReadout(running?'running':'paused');};els.resetBtn.onclick=reinitialize;els.defaultPresetBtn.onclick=()=>{els.g.value=els.gNumber.value='1.0';els.kappa1.value=els.kappa1Number.value='5.0';els.kappa2.value=els.kappa2Number.value='0.5';els.L.value=els.LNumber.value='200';els.N.value=els.NNumber.value='2000';els.dt.value=els.dtNumber.value='0.012';els.topCharge.value=els.topChargeNumber.value='0';els.relaxSteps.value=els.relaxStepsNumber.value='250';reinitialize();};els.nearThresholdPresetBtn.onclick=()=>{els.g.value=els.gNumber.value='1.58';els.kappa1.value=els.kappa1Number.value='1.0';els.kappa2.value=els.kappa2Number.value='1.0';els.L.value=els.LNumber.value='240';els.N.value=els.NNumber.value='2800';els.dt.value=els.dtNumber.value='0.008';els.relaxSteps.value=els.relaxStepsNumber.value='300';reinitialize();};els.bcPeriodicBtn.onclick=()=>setBC('periodic');els.bcDirichletBtn.onclick=()=>setBC('dirichlet');els.bcNeumannBtn.onclick=()=>setBC('neumann');pairs.forEach(([a,b])=>{els[a].oninput=()=>{els[b].value=els[a].value;reinitialize();};els[b].oninput=()=>{els[a].value=els[b].value;reinitialize();};});els.viewMode.oninput=reinitialize;initialize();tick();